# Generated by Django 4.1.7 on 2023-03-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_editor', '0003_contacttext_first_name_contacttext_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttext',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contacttext',
            name='last_name',
        ),
    ]
