# Generated by Django 4.1.7 on 2023-03-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_editor', '0004_remove_contacttext_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttext',
            name='first_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='last_name',
            field=models.TextField(blank=True),
        ),
    ]
