# Generated by Django 4.1.7 on 2023-03-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_editor', '0005_contacttext_first_name_contacttext_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttext',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='contacttext',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
