# Generated by Django 4.1.7 on 2023-03-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_editor', '0006_rename_first_name_contacttext_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttext',
            name='academic_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='adress_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='company_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='facebook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='fax_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='house_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='mobile_phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='region',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='street',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='web_site',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacttext',
            name='zip',
            field=models.TextField(blank=True),
        ),
    ]
